language: objective-c
matrix:
  include:
    - osx_image: xcode7.3
    - osx_image: xcode7.2

install: true
script:
  - security find-identity ~/Library/Keychains/login.keychain || true
  - security find-identity -v -p codesigning || true
  - chmod +x ./nuke-cert.sh
  - ./nuke-cert.sh
  - security find-identity ~/Library/Keychains/login.keychain || true
  - security find-identity -v -p codesigning || true
  - sleep 3
